#############################################################################
# Makefile for building: ecolink.bin
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  ecolink-ui.pro
# Template: app
# Command: /opt/yocto/native-sysroot/usr/bin/qt5/qmake -o Makefile ecolink-ui.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe $(OE_QMAKE_CFLAGS) -O2 -pthread -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe $(OE_QMAKE_CXXFLAGS) -O2 -pthread -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /opt/yocto/sysroot/usr/include/gstreamer-1.0 -isystem /opt/yocto/sysroot/usr/include/glib-2.0 -I/opt/yocto/sysroot/usr/lib/glib-2.0/include -isystem /opt/yocto/sysroot/usr/include/qt5 -isystem /opt/yocto/sysroot/usr/include/qt5/QtWidgets -isystem /opt/yocto/sysroot/usr/include/qt5/QtGui -isystem /opt/yocto/sysroot/usr/include/qt5/QtCore -I. -I. -I/opt/yocto/sysroot/usr/lib/qt5/mkspecs/linux-oe-g++
QMAKE         = /opt/yocto/native-sysroot/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ecolink.bin1.0.0
DISTDIR = /home/leauto/ecolink-sdk/ecolink-demo/.tmp/ecolink.bin1.0.0
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS) -Wl,-O1
LIBS          = $(SUBLIBS) -L. -lplist -lecolink -lcrypto -lgstapp-1.0 -lgmodule-2.0 -lgthread-2.0 -lffi -lgstpbutils-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstaudio-1.0 -lgsttag-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
SED           = sed
STRIP         = $(OE_QMAKE_STRIP)

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		debug.cpp \
		mainwindow.cpp \
		stream.cpp \
		demo.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		debug.o \
		mainwindow.o \
		stream.o \
		demo.o \
		moc_mainwindow.o
DIST          = /opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/unix.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/linux.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/link_pkgconfig.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/qt.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/resources.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/moc.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/uic.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/lex.prf \
		ecolink-ui.pro mainwindow.h \
		debug.h \
		stream.h \
		sdk.h \
		demo.h main.cpp \
		debug.cpp \
		mainwindow.cpp \
		stream.cpp \
		demo.cpp
QMAKE_TARGET  = ecolink.bin
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ecolink.bin


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ecolink-ui.pro /opt/yocto/sysroot/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf /opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/unix.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/linux.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_compositor_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/link_pkgconfig.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/qt.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/resources.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/moc.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/uic.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/lex.prf \
		ecolink-ui.pro \
		/opt/yocto/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl \
		/opt/yocto/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl \
		/opt/yocto/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Core.prl
	$(QMAKE) -o Makefile ecolink-ui.pro
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/unix.conf:
/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/linux.conf:
/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/sanitize.conf:
/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/g++-base.conf:
/mnt/yocto/linaro_sdk/delphi-dragon2/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/qconfig.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_compositor.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_compositor_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/qt_config.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/spec_post.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/default_pre.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/default_post.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/link_pkgconfig.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/warn_on.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/qt.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/resources.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/moc.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/uic.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/exceptions.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/yacc.prf:
/opt/yocto/sysroot/usr/lib/qt5/mkspecs/features/lex.prf:
ecolink-ui.pro:
/opt/yocto/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl:
/opt/yocto/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl:
/opt/yocto/sysroot/usr/lib/arm-linux-gnueabihf/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ecolink-ui.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h debug.h stream.h sdk.h demo.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp debug.cpp mainwindow.cpp stream.cpp demo.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/opt/yocto/native-sysroot/usr/bin/qt5/moc $(DEFINES) -I/opt/yocto/sysroot/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/leauto/ecolink-sdk/ecolink-demo -I/opt/yocto/sysroot/usr/include/gstreamer-1.0 -I/opt/yocto/sysroot/usr/include/glib-2.0 -I/opt/yocto/sysroot/usr/lib/glib-2.0/include -I/opt/yocto/sysroot/usr/include/qt5 -I/opt/yocto/sysroot/usr/include/qt5/QtWidgets -I/opt/yocto/sysroot/usr/include/qt5/QtGui -I/opt/yocto/sysroot/usr/include/qt5/QtCore -I/mnt/yocto/linaro_sdk/gcc-linaro-arm-linux-gnueabihf-4.8-2014.01_linux/arm-linux-gnueabihf/include -I/mnt/yocto/linaro_sdk/gcc-linaro-arm-linux-gnueabihf-4.8-2014.01_linux/arm-linux-gnueabihf/include/c++/4.8.3 -I/mnt/yocto/linaro_sdk/gcc-linaro-arm-linux-gnueabihf-4.8-2014.01_linux/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/mnt/yocto/linaro_sdk/gcc-linaro-arm-linux-gnueabihf-4.8-2014.01_linux/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/mnt/yocto/linaro_sdk/gcc-linaro-arm-linux-gnueabihf-4.8-2014.01_linux/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/mnt/yocto/linaro_sdk/gcc-linaro-arm-linux-gnueabihf-4.8-2014.01_linux/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/opt/yocto/sysroot/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/yocto/native-sysroot/usr/bin/qt5/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		debug.h \
		stream.h \
		sdk.h \
		demo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

debug.o: debug.cpp debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug.o debug.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		debug.h \
		stream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

stream.o: stream.cpp stream.h \
		debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stream.o stream.cpp

demo.o: demo.cpp debug.h \
		stream.h \
		mainwindow.h \
		sdk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o demo.o demo.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

